# Generated by Django 3.0.3 on 2020-04-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomment',
            name='like_num',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='num',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='sid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='snow_nlp',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='score',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='star',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='tag',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='tfidf',
            field=models.TextField(null=True),
        ),
    ]
