# Generated by Django 3.0.3 on 2020-04-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookInfo', '0003_bookcomment_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name': '图书信息', 'verbose_name_plural': '图书信息'},
        ),
        migrations.AlterModelTable(
            name='bookinfo',
            table=None,
        ),
    ]
