# Generated by Django 3.0.3 on 2020-04-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookInfo', '0004_auto_20200414_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcomment',
            options={'verbose_name': '图书评论', 'verbose_name_plural': '图书评论'},
        ),
        migrations.AlterModelTable(
            name='bookcomment',
            table=None,
        ),
    ]
