# Generated by Django 3.0.3 on 2020-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookInfo', '0005_auto_20200414_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='pesg_list',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='pesg_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='word_cloud',
            field=models.TextField(null=True),
        ),
    ]
