# Generated by Django 3.0.3 on 2020-04-23 13:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookInfo', '0006_auto_20200423_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='pesg_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
