# Generated by Django 3.0.3 on 2020-04-24 06:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookInfo', '0007_auto_20200423_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='pesg_name',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
