# Generated by Django 3.0.3 on 2020-04-24 06:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookInfo', '0008_auto_20200424_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='tfidf',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
